# Generated by Django 2.2 on 2019-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(verbose_name='date from')),
                ('date_to', models.DateTimeField(verbose_name='date to')),
                ('questions', models.ManyToManyField(to='testapp.Question')),
            ],
        ),
    ]
