# Generated by Django 2.2 on 2019-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190425_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(editable=False, to='testapp.Question'),
        ),
    ]
